
all: zad3

test: zad3
	echo "Glebokosc: 8"
	./zad3 . szukany_napis 8
	echo ""
	echo "Glebokosc: 4"
	./zad3 . szukany_napis 4
	echo ""
	echo "Glebokosc: 2"
	./zad3 . szukany_napis 2

zad3:
	gcc -Wall zad3.c -o zad3

clean:
	rm zad3